project:
  type: website

website:
  title: "Shiny for Python Workshop"
  sidebar:
    contents:
      - getting-started.qmd
      - reactivity.qmd
  navbar:
    tools: 
      - icon: github
        href: https://github.com/rstudio/shiny-python-workshop-2023
      - icon: fa-dicord
        href: https://discord.gg/AQVJzG2bnN
    left:
      - href: index.qmd
        text: Home

filters:
  - shinylive

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



